name: Run Bash Loop

on:
  push:
    branches:
      - main

jobs:
  run-loop:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run bash loop script 1
        run: |
          echo "Starting loop 2"
          for i in {1..20}
          do
            echo "Loop iteration $i"
            sleep 1
          done
          echo "Loop finished 1"
      - name: Run bash loop script 2
        run: |
          echo "Starting loop 2"
          for i in {1..10}
          do
            echo "Loop iteration $i"
            sleep 1
          done
          echo "Loop finished 2"
