name: Run Bash Loop

on:
  push:
    branches:
      - main

jobs:
  run-loop:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run bash loop script 1
        run: |
          ps aux | grep "jitconfig"
